<div id="banner-bottom" class="startup-banner">
    <div class="notice">
        Check out my company, browserling!
    </div>
    <div class="startup browserling">
        <a href="http://browserling.com"
        ><img src="/images/logo/browserling.png"
        width="206" height="70"></a>
        <br>
        <a href="http://browserling.com">cross-browser testing from your
        browser!</a>
    </div>
    <div class="startup testling">
        <a href="http://testling.com"
        ><img src="/images/logo/testling.png"
        width="156" height="70"></a>
        <br>
        <a href="http://testling.com">javascript tests in all the browsers!</a>
    </div>
</div>
<div id="footer">
<a
    rel="license"
    href="http://creativecommons.org/licenses/by-sa/3.0/us/"
><img
    alt="Creative Commons License"
    style="border-width:0"
    src="http://i.creativecommons.org/l/by-sa/3.0/us/80x15.png"
/></a>
</div>
