<div id="header">
    <a href="$ blogRoot $/"><img
        id="header-img"
        src="$ blogRoot $/images/universe-of-discord.png"
        alt="the universe of discord"
        width="600px" height="148px"
    /></a>
</div>
<div id="sidebar-container">
    <img
        id="robot"
        src="$ blogRoot $/images/robot.png"
        width="165px" height="195px"
    />
    $ sidebar() $
</div>
<div id="startup-banner">
    <div id="browserling" class="startup">
        <a href="http://browserling.com"
        ><img src="/images/logo/browserling.png"
        width="206" height="70"></a>
        <br>
        <a href="http://browserling.com">cross-browser testing from your
        browser!</a>
    </div>
    <div id="testling" class="startup">
        <a href="http://testling.com"
        ><img src="/images/logo/testling.png"
        width="156" height="70"></a>
        <br>
        <a href="http://testling.com">javascript tests in all the browsers!</a>
    </div>
</div>
